language: python
cache: pip
sudo: false

jobs:
    include: 
    - name: lint
      stage: lint/unit
      script:
        - make lint
    - name: unit
      script:
        - make test
    - stage: deploy
      if: branch = master AND type = push
      python: 
        - '3.6'
      script: 
        - flit publish

after_success:
    - codecov --env TRAVIS_OS_NAME
      
install:
- pip install -r requirements.txt
